language: python
python:
  - "3.3"
install: pip install -r requirements.txt --use-mirrors
script:  ./manage.py test
before_script:
  - psql -c 'create database pypo;' -U postgres
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
